//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrentGame
    {
        public int CurrentGameID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TrainerID { get; set; }
    }
}
