//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGame
    {
        public tblGame()
        {
            this.tblGameDisplayObjects = new HashSet<tblGameDisplayObject>();
            this.tblGameSensors = new HashSet<tblGameSensor>();
            this.tblResults = new HashSet<tblResult>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameHR { get; set; }
        public string NameENG { get; set; }
        public Nullable<bool> IsRandom { get; set; }
        public Nullable<int> RandomValue { get; set; }
        public Nullable<short> RandomType { get; set; }
        public Nullable<bool> IsTimeLimit { get; set; }
        public Nullable<int> TimeLimit { get; set; }
        public string Description { get; set; }
        public string Objectives { get; set; }
        public string Definition { get; set; }
        public string DescriptionHR { get; set; }
        public Nullable<int> NumShownFields { get; set; }
        public Nullable<int> NumRepetition { get; set; }
        public string RandomFields { get; set; }
        public Nullable<bool> QuickGamePool { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.TimeSpan> MinStayTime { get; set; }
        public Nullable<System.TimeSpan> MaxStayTime { get; set; }
        public Nullable<System.TimeSpan> MinFlyTime { get; set; }
        public Nullable<System.TimeSpan> MaxFlyTime { get; set; }
        public Nullable<int> StartField { get; set; }
        public Nullable<int> Countdown { get; set; }
        public Nullable<bool> LegLeft { get; set; }
        public Nullable<bool> LegRight { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> DescriptionDuration { get; set; }
        public Nullable<int> Reaction { get; set; }
        public Nullable<System.TimeSpan> ReactionTime { get; set; }
        public string ReactionFootDef { get; set; }
        public Nullable<int> ReactionSignalID { get; set; }
        public Nullable<int> ReactionTypeID { get; set; }
        public Nullable<int> MemoryTypeID { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual ICollection<tblGameDisplayObject> tblGameDisplayObjects { get; set; }
        public virtual ICollection<tblGameSensor> tblGameSensors { get; set; }
        public virtual ICollection<tblResult> tblResults { get; set; }
    }
}
