//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGameSensor
    {
        public int ID { get; set; }
        public Nullable<short> Number1 { get; set; }
        public Nullable<short> Number2 { get; set; }
        public bool IsValueCompare { get; set; }
        public Nullable<short> ValueCompareType { get; set; }
        public Nullable<short> Number1ValueType { get; set; }
        public string Number1Value { get; set; }
        public Nullable<short> Number2ValueType { get; set; }
        public string Number2Value { get; set; }
        public Nullable<int> TimeLimit { get; set; }
        public int GameID { get; set; }
    
        public virtual tblGame tblGame { get; set; }
    }
}
