//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGameCombination
    {
        public int GameCombinationID { get; set; }
        public string CombinationName { get; set; }
        public Nullable<int> GameID1 { get; set; }
        public Nullable<int> GameID2 { get; set; }
        public Nullable<int> GameID3 { get; set; }
        public Nullable<int> GameID4 { get; set; }
        public Nullable<int> GameID5 { get; set; }
        public Nullable<int> GameID6 { get; set; }
        public Nullable<int> GameID7 { get; set; }
        public Nullable<int> GameID8 { get; set; }
        public Nullable<int> GameID9 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Modification { get; set; }
    }
}
