//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemoryType
    {
        public int MemoryTypeID { get; set; }
        public string MemoryType { get; set; }
        public Nullable<bool> Active { get; set; }
        public string MemoryTypeDescription { get; set; }
    }
}
