//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public tblResult()
        {
            this.tblSchedules = new HashSet<tblSchedule>();
            this.tblSpeedEntries = new HashSet<tblSpeedEntry>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<System.DateTime> LapTime { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<int> ContactsLeft { get; set; }
        public Nullable<int> ContactsRight { get; set; }
    
        public virtual tblGame tblGame { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblSchedule> tblSchedules { get; set; }
        public virtual ICollection<tblSpeedEntry> tblSpeedEntries { get; set; }
    }
}
