//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpeedEntry
    {
        public int ID { get; set; }
        public int MatID { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int Interval { get; set; }
        public int SensorTypeID { get; set; }
        public int InstanceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> ResultID { get; set; }
    
        public virtual tblResult tblResult { get; set; }
        public virtual tblSensorType tblSensorType { get; set; }
    }
}
