//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchedule
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> ResultID { get; set; }
    
        public virtual tblResult tblResult { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUserGroup tblUserGroup { get; set; }
    }
}
