//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserGroup
    {
        public tblUserGroup()
        {
            this.tblSchedules = new HashSet<tblSchedule>();
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameHR { get; set; }
        public string NameENG { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    
        public virtual ICollection<tblSchedule> tblSchedules { get; set; }
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
