//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwChaseSymbol
    {
        public int ChaseSymbolID { get; set; }
        public byte[] SymbolPic { get; set; }
        public string SymbolSign { get; set; }
        public Nullable<int> FieldID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> GameID { get; set; }
        public byte[] Img { get; set; }
        public string Word { get; set; }
        public string Color { get; set; }
        public string Fx { get; set; }
    }
}
