//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGameSpeedChase
    {
        public int GameID { get; set; }
        public string F01Name { get; set; }
        public string F02Name { get; set; }
        public string F03Name { get; set; }
        public string F04Name { get; set; }
        public string F05Name { get; set; }
        public string F06Name { get; set; }
        public string F07Name { get; set; }
        public string F08Name { get; set; }
        public string F09Name { get; set; }
        public string F10Name { get; set; }
        public string F11Name { get; set; }
        public string F12Name { get; set; }
        public string F13Name { get; set; }
        public string F14Name { get; set; }
        public string F15Name { get; set; }
        public string F16Name { get; set; }
        public string F17Name { get; set; }
        public string F18Name { get; set; }
        public string F19Name { get; set; }
        public string F20Name { get; set; }
        public string F21Name { get; set; }
        public string F22Name { get; set; }
        public string F23Name { get; set; }
        public string F24Name { get; set; }
        public string F25Name { get; set; }
        public string F26Name { get; set; }
        public string F27Name { get; set; }
        public string F28Name { get; set; }
        public string F29Name { get; set; }
        public string F30Name { get; set; }
        public string F31Name { get; set; }
        public string F32Name { get; set; }
        public string F01Word { get; set; }
        public string F02Word { get; set; }
        public string F03Word { get; set; }
        public string F04Word { get; set; }
        public string F05Word { get; set; }
        public string F06Word { get; set; }
        public string F07Word { get; set; }
        public string F08Word { get; set; }
        public string F09Word { get; set; }
        public string F10Word { get; set; }
        public string F11Word { get; set; }
        public string F12Word { get; set; }
        public string F13Word { get; set; }
        public string F14Word { get; set; }
        public string F15Word { get; set; }
        public string F16Word { get; set; }
        public string F17Word { get; set; }
        public string F18Word { get; set; }
        public string F19Word { get; set; }
        public string F20Word { get; set; }
        public string F21Word { get; set; }
        public string F22Word { get; set; }
        public string F23Word { get; set; }
        public string F24Word { get; set; }
        public string F25Word { get; set; }
        public string F26Word { get; set; }
        public string F27Word { get; set; }
        public string F28Word { get; set; }
        public string F29Word { get; set; }
        public string F30Word { get; set; }
        public string F31Word { get; set; }
        public string F32Word { get; set; }
        public string F01Fx { get; set; }
        public string F02Fx { get; set; }
        public string F03Fx { get; set; }
        public string F04Fx { get; set; }
        public string F05Fx { get; set; }
        public string F06Fx { get; set; }
        public string F07Fx { get; set; }
        public string F08Fx { get; set; }
        public string F09Fx { get; set; }
        public string F10Fx { get; set; }
        public string F11Fx { get; set; }
        public string F12Fx { get; set; }
        public string F13Fx { get; set; }
        public string F14Fx { get; set; }
        public string F15Fx { get; set; }
        public string F16Fx { get; set; }
        public string F17Fx { get; set; }
        public string F18Fx { get; set; }
        public string F19Fx { get; set; }
        public string F20Fx { get; set; }
        public string F21Fx { get; set; }
        public string F22Fx { get; set; }
        public string F23Fx { get; set; }
        public string F24Fx { get; set; }
        public string F25Fx { get; set; }
        public string F26Fx { get; set; }
        public string F27Fx { get; set; }
        public string F28Fx { get; set; }
        public string F29Fx { get; set; }
        public string F30Fx { get; set; }
        public string F31Fx { get; set; }
        public string F32Fx { get; set; }
    }
}
