//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGame
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsRandom { get; set; }
        public Nullable<int> RandomValue { get; set; }
        public Nullable<short> RandomType { get; set; }
        public Nullable<bool> IsTimeLimit { get; set; }
        public Nullable<int> TimeLimit { get; set; }
        public string Description { get; set; }
        public string Objectives { get; set; }
        public string Definition { get; set; }
        public string RandomFields { get; set; }
        public int RF01 { get; set; }
        public int RF02 { get; set; }
        public int RF03 { get; set; }
        public int RF04 { get; set; }
        public int RF05 { get; set; }
        public int RF06 { get; set; }
        public int RF07 { get; set; }
        public int RF08 { get; set; }
        public int RF09 { get; set; }
        public Nullable<int> RF10 { get; set; }
        public Nullable<int> RF11 { get; set; }
        public Nullable<int> RF12 { get; set; }
        public Nullable<int> RF13 { get; set; }
        public Nullable<int> RF14 { get; set; }
        public Nullable<int> RF15 { get; set; }
        public Nullable<int> RF16 { get; set; }
        public Nullable<int> RF17 { get; set; }
        public Nullable<int> RF18 { get; set; }
        public Nullable<int> RF19 { get; set; }
        public Nullable<int> RF20 { get; set; }
        public Nullable<int> RF21 { get; set; }
        public Nullable<int> RF22 { get; set; }
        public Nullable<int> RF23 { get; set; }
        public Nullable<int> RF24 { get; set; }
        public Nullable<int> RF25 { get; set; }
        public Nullable<int> RF26 { get; set; }
        public Nullable<int> RF27 { get; set; }
        public Nullable<int> RF28 { get; set; }
        public Nullable<int> RF29 { get; set; }
        public Nullable<int> RF30 { get; set; }
        public Nullable<int> RF31 { get; set; }
        public Nullable<int> RF32 { get; set; }
        public string CategoryName { get; set; }
        public int MiddleFieldsAsOne { get; set; }
        public int MiddleFieldsAsTwo { get; set; }
        public int MiddleFieldsAsFour { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Distance { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> NoOfPlays { get; set; }
        public string LastPlayed { get; set; }
        public Nullable<int> MemoryTypeID { get; set; }
    }
}
