//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGameCombination
    {
        public int GameCombinationID { get; set; }
        public string CombinationName { get; set; }
        public Nullable<int> GameID1 { get; set; }
        public Nullable<int> GameID2 { get; set; }
        public Nullable<int> GameID3 { get; set; }
        public Nullable<int> GameID4 { get; set; }
        public Nullable<int> GameID5 { get; set; }
        public Nullable<int> GameID6 { get; set; }
        public Nullable<int> GameID7 { get; set; }
        public Nullable<int> GameID8 { get; set; }
        public Nullable<int> GameID9 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Modification { get; set; }
        public string Game1Name { get; set; }
        public string Game2Name { get; set; }
        public string Game3Name { get; set; }
        public string Game4Name { get; set; }
        public string Game5Name { get; set; }
        public string Game6Name { get; set; }
        public string Game7Name { get; set; }
        public string Game8Name { get; set; }
        public string Game9Name { get; set; }
        public int ID { get; set; }
    }
}
