//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGroupMember
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int UserGroupID { get; set; }
        public int SportID { get; set; }
        public bool IsActiv { get; set; }
        public System.DateTime Birthday { get; set; }
        public string GroupName { get; set; }
        public string GroupNameHR { get; set; }
        public string GroupNameENG { get; set; }
        public bool Active { get; set; }
        public string SportName { get; set; }
    }
}
