//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTemplate
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public bool IsActive { get; set; }
        public int Radio3 { get; set; }
        public int Radio5 { get; set; }
        public int Radio7 { get; set; }
        public int Radio9 { get; set; }
        public int RadioX { get; set; }
    }
}
