//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTemp
    {
        public int ID { get; set; }
        public Nullable<int> F01ID { get; set; }
        public Nullable<int> F02ID { get; set; }
        public Nullable<int> F03ID { get; set; }
        public Nullable<int> F04ID { get; set; }
        public Nullable<int> F05ID { get; set; }
        public Nullable<int> F06ID { get; set; }
        public Nullable<int> F07ID { get; set; }
        public Nullable<int> F08ID { get; set; }
        public Nullable<int> F09ID { get; set; }
        public Nullable<int> F10ID { get; set; }
        public Nullable<int> F11ID { get; set; }
        public Nullable<int> F12ID { get; set; }
        public Nullable<bool> F01Active { get; set; }
        public Nullable<bool> F02Active { get; set; }
        public Nullable<bool> F03Active { get; set; }
        public Nullable<bool> F04Active { get; set; }
        public Nullable<bool> F05Active { get; set; }
        public Nullable<bool> F06Active { get; set; }
        public Nullable<bool> F07Active { get; set; }
        public Nullable<bool> F08Active { get; set; }
        public Nullable<bool> F09Active { get; set; }
        public Nullable<bool> F10Active { get; set; }
        public Nullable<bool> F11Active { get; set; }
        public Nullable<bool> F12Active { get; set; }
        public Nullable<bool> F01PhotoCell { get; set; }
        public Nullable<bool> F02PhotoCell { get; set; }
        public Nullable<bool> F03PhotoCell { get; set; }
        public Nullable<bool> F04PhotoCell { get; set; }
        public Nullable<bool> F05PhotoCell { get; set; }
        public Nullable<bool> F06PhotoCell { get; set; }
        public Nullable<bool> F07PhotoCell { get; set; }
        public Nullable<bool> F08PhotoCell { get; set; }
        public Nullable<bool> F09PhotoCell { get; set; }
        public Nullable<bool> F10PhotoCell { get; set; }
        public Nullable<bool> F11PhotoCell { get; set; }
        public Nullable<bool> F12PhotoCell { get; set; }
        public bool IsActive { get; set; }
        public int GameID { get; set; }
        public string F01Name { get; set; }
        public string F02Name { get; set; }
        public string F03Name { get; set; }
        public string F04Name { get; set; }
        public string F05Name { get; set; }
        public string F06Name { get; set; }
        public string F07Name { get; set; }
        public string F08Name { get; set; }
        public string F09Name { get; set; }
        public string F10Name { get; set; }
        public string F11Name { get; set; }
        public string F12Name { get; set; }
        public string F13Name { get; set; }
        public string F14Name { get; set; }
        public string F15Name { get; set; }
        public string F16Name { get; set; }
        public string F17Name { get; set; }
        public string F18Name { get; set; }
        public string F19Name { get; set; }
        public string F20Name { get; set; }
        public string F21Name { get; set; }
        public string F22Name { get; set; }
        public string F23Name { get; set; }
        public string F24Name { get; set; }
        public string F25Name { get; set; }
        public string F26Name { get; set; }
        public string F27Name { get; set; }
        public string F28Name { get; set; }
        public string F29Name { get; set; }
        public string F30Name { get; set; }
        public string F31Name { get; set; }
        public string F32Name { get; set; }
        public string F01Word { get; set; }
        public string F02Word { get; set; }
        public string F03Word { get; set; }
        public string F04Word { get; set; }
        public string F05Word { get; set; }
        public string F06Word { get; set; }
        public string F07Word { get; set; }
        public string F08Word { get; set; }
        public string F09Word { get; set; }
        public string F10Word { get; set; }
        public string F11Word { get; set; }
        public string F12Word { get; set; }
        public string F01Fx { get; set; }
        public string F02Fx { get; set; }
        public string F03Fx { get; set; }
        public string F04Fx { get; set; }
        public string F05Fx { get; set; }
        public string F06Fx { get; set; }
        public string F07Fx { get; set; }
        public string F08Fx { get; set; }
        public string F09Fx { get; set; }
        public string F10Fx { get; set; }
        public string F11Fx { get; set; }
        public string F12Fx { get; set; }
    }
}
