//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUser
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PIN { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<long> RFID { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZIP { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public Nullable<int> SportID { get; set; }
        public bool HasPicture { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string SportName { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Role { get; set; }
        public byte[] Picture { get; set; }
    }
}
